### ISSUE TITLE
Is `AWS.Lambda.Runtime.Value` redundant?

### ISSUE THREAD

**Issue by endgame** [Nike-Inc/hal#67]
Aeson provides `instance FromJSON Value`, so it seems like the functions in this module could be subsumed by the ones in `AWS.Lambda.Runtime`.

**Comment by IamfromSpace** [comment]
It sort of is and isn't.  For 99% of folks writing lambdas, a translation to their type is an assumed invariant.  Arguably, all handlers should have a `Value` or `Maybe a` or `Either x a` as their input, but a majority of cases just don't care.

It is however invariant that AWS will give you valid JSON.  The split internally allows the "core" runtime (the Value runtime) to safely capture everything here, and not worry about how to handle errors in translation.  It gives a nice clean separation (though, it does couple to aeson).

The default runtime then is a concession to real world usage, in the same way that the pure or IO runtimes are, but connected only by combinators, rather than being promoted into core logic.

However, yes, to a user, with `Value` as your input, it's essentially identical (and possibly _is_ identical if the compiler is smart enough).  I suppose the Value runtime is also there as a major flag to the user that _that_ is in fact, the core of lambda.  If they cannot trust their clients, they'll need to handle these failure explicitly.

Happy to discuss further; I'll keep this open until you're satisfied (at which point you're welcome to close it).

**Comment by endgame** [comment]
Yeah that makes a lot of sense. I suppose the guts of the implementation have to go somewhere.
